### ISSUE TITLE
Intl version within flutter_localizations makes version 3.2.1 of decimal impossible to use on Flutter v3.29.3

### ISSUE THREAD

**Issue by large** [a14n/dart-decimal#113]
Running Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64)

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Multilang support
    sdk: flutter
  decimal: ^3.2.1
```

Will cause error in handling

> Because decimal 3.2.1 depends on intl ^0.20.0 and no versions of decimal match >3.2.1 <4.0.0, decimal ^3.2.1 requires intl ^0.20.0.
> So, because app depends on both intl ^0.19.0 and decimal ^3.2.1, version solving failed.

So you have to have to downgrade to 3.0.2 for "success".
But then we are missing out on the improved performance on 3.2.x ;)

Consider future released with a looser version handling of sub packages, if possible.
